sudo: required

language: generic

services:
 - docker

before_install:
 - echo "start creating an image with Dockerfile"
 - docker build -t kyh7461/reactapp -f dockerfile.dev ./

script:
 - docker run -e CI=true kyh7461/reactapp npm run test -- --coverage

after_success:
 - echo "Test success"